# Generated by Django 5.2.14 on 2026-07-29 10:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EidCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid_name', models.CharField(choices=[('EID_UL_FITR', 'Eid-ul-Fitr'), ('EID_UL_ADHA', 'Eid-ul-Adha')], max_length=20)),
                ('date', models.DateField(help_text='Eid ki tareekh')),
                ('imam_name', models.CharField(help_text='Imam ka naam', max_length=100)),
                ('imam_type', models.CharField(choices=[('RESIDENT', 'Resident Imam (Hamari Masjid Ke Imam)'), ('GUEST', 'Guest Imam (Dusri Masjid Ke Imam)')], default='RESIDENT', max_length=10)),
                ('amount_collected', models.DecimalField(decimal_places=2, help_text='Total eid amount', max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(help_text='What was the money spent on? (Clear detail)', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('UTILITIES', 'Electricity / Water Bills'), ('REPAIR', 'Repairing & Maintenance'), ('CLEANING', 'Cleaning & Supplies'), ('EVENT', 'Event / Program Expense'), ('OTHER', 'Other Expense')], default='OTHER', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ImamSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imam_name', models.CharField(default='Imam Masjid', max_length=100)),
                ('month_year', models.DateField(help_text='Select month (e.g., 2026-07-01 for July 2026)')),
                ('total_salary', models.DecimalField(decimal_places=2, help_text='Per Month Total Salary', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='LandLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_area', models.CharField(default='2 Acres', max_length=50)),
                ('tenant_name', models.CharField(help_text='Thekedar name', max_length=100)),
                ('tenant_contact', models.CharField(blank=True, help_text='Phone number', max_length=20, null=True)),
                ('start_date', models.DateField(help_text='Theka start date')),
                ('end_date', models.DateField(help_text='Theka end date')),
                ('duration_years', models.PositiveIntegerField(help_text='Theka duration')),
                ('total_agreed_amount', models.DecimalField(decimal_places=2, help_text='Total amount (e.g. 2,000,000)', max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('day_type', models.CharField(choices=[('THURSDAY', 'Thursday Collection'), ('FRIDAY', 'Friday Collection')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total donation', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Extra detail (optional)', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImamSalaryInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Installment / Single payment amount', max_digits=10)),
                ('notes', models.CharField(blank=True, help_text='e.g. 1st installment, advance, full pay', max_length=255, null=True)),
                ('salary_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='donation.imamsalary')),
            ],
        ),
        migrations.CreateModel(
            name='LandLeasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('amount_received', models.DecimalField(decimal_places=2, help_text='Installment recieved', max_digits=10)),
                ('notes', models.CharField(blank=True, help_text='e.g. Installment 1, 2, etc', max_length=255, null=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='donation.landlease')),
            ],
        ),
    ]
