# Generated by Django 5.2.14 on 2026-07-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eidcollection',
            name='imam_type',
            field=models.CharField(choices=[('Qari Abbas', 'Qari Abbas Imam (Jameya Masjid Ke Imam)'), ('Hafiz Shehzab', 'Hafiz Shehzab Imam (Chhoti Masjid Ke Imam)')], default='RESIDENT', max_length=100),
        ),
    ]
