# Generated by Django 5.2.14 on 2026-08-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_alter_eidcollection_imam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyincome',
            name='day_type',
            field=models.CharField(choices=[('THURSDAY', 'Thursday Collection'), ('FRIDAY', 'Friday Collection'), ('OTHER', 'Other Collection')], max_length=20),
        ),
    ]
