# Generated by Django 5.2.14 on 2026-08-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_alter_weeklyincome_day_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='imamsalary',
            name='yearly_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Per Year Total Salary', max_digits=12),
        ),
    ]
